#!/bin/bash

echo Reiniciar mosquitto
sleep 60
service mosquitto restart
echo Detener mongodb
sleep 1
service mongodb stop
echo Iniciar mongod
sleep 10
mongod &
echo Iniciar node app.js
sleep 10
cd /home/pi/totem/nodejs
node app.js &
